export const siteConfig = {
  name: "Savannah Rodent Control",
  primaryService: "Rodent Control",
  city: "Savannah",
  state: "GA",
  stateFull: "Georgia",
  phone: "(912) 305-0115",
  phoneRaw: "9123050115",
  email: "info@rodentcontrolsavannah.com",
  domain: "rodentcontrolsavannah.com",
  url: "https://rodentcontrolsavannah.com",
  hours: "Mon–Sat 7AM–10PM",
  hoursSchema: "Mo-Sa 07:00-22:00",
  founded: "2025",
  address: "412 E Park Ave, Savannah, GA 31401",
  street: "412 E Park Ave",
  zip: "31401",
  lat: "32.0535",
  lng: "-81.0998",
  twitter: "https://x.com/SavannahRodentCtrl",
  instagram: "https://www.instagram.com/savannahrodentcontrol/",
} as const

export const services = [
  { slug: "rat-control", title: "Rat Control" },
  { slug: "mice-control", title: "Mice Control" },
  { slug: "rodent-removal", title: "Rodent Removal" },
  { slug: "emergency-rodent-removal", title: "Emergency Rodent Removal" },
  { slug: "same-day-rat-removal", title: "Same-Day Rat Removal" },
  { slug: "mouse-infestation-treatment", title: "Mouse Infestation Treatment" },
  { slug: "residential-rodent-control", title: "Residential Rodent Control" },
  { slug: "commercial-rodent-control", title: "Commercial Rodent Control" },
  { slug: "apartment-property-management-rodent-control", title: "Apartment & Property Management Rodent Control" },
  { slug: "warehouse-rodent-control", title: "Warehouse Rodent Control" },
  { slug: "rodent-exclusion-services", title: "Rodent Exclusion Services" },
  { slug: "rat-proofing-services", title: "Rat Proofing Services" },
  { slug: "mouse-proofing-sealing-entry-points", title: "Mouse Proofing & Sealing Entry Points" },
  { slug: "crawl-space-rodent-sealing", title: "Crawl Space Rodent Sealing" },
  { slug: "attic-rodent-proofing", title: "Attic Rodent Proofing" },
  { slug: "rodent-droppings-cleanup", title: "Rodent Droppings Cleanup" },
  { slug: "rat-nest-removal", title: "Rat Nest Removal" },
  { slug: "attic-rodent-cleanup-sanitization", title: "Attic Rodent Cleanup & Sanitization" },
  { slug: "insulation-replacement-after-rodent-damage", title: "Insulation Replacement After Rodent Damage" },
  { slug: "rodent-inspection-services", title: "Rodent Inspection Services" },
]

export const areas = [
  { slug: "ardsley-park", name: "Ardsley Park", zip: "31405" },
  { slug: "baldwin-park", name: "Baldwin Park", zip: "31404" },
  { slug: "barry", name: "Barry", zip: "31408" },
  { slug: "beach-institute", name: "Beach Institute", zip: "31401" },
  { slug: "beechwood", name: "Beechwood", zip: "31419" },
  { slug: "berkshire-woods", name: "Berkshire Woods", zip: "31419" },
  { slug: "bingville", name: "Bingville", zip: "31415" },
  { slug: "bonaventure", name: "Bonaventure", zip: "31404" },
  { slug: "bradley-point", name: "Bradley Point", zip: "31419" },
  { slug: "burnside-island", name: "Burnside Island", zip: "31406" },
  { slug: "cann-park", name: "Cann Park", zip: "31405" },
  { slug: "carver-heights", name: "Carver Heights", zip: "31404" },
  { slug: "chatham-parkway", name: "Chatham Parkway", zip: "31405" },
  { slug: "coffee-bluff", name: "Coffee Bluff", zip: "31419" },
  { slug: "cuyler-brownsville", name: "Cuyler Brownsville", zip: "31415" },
  { slug: "deerfield", name: "Deerfield", zip: "31406" },
  { slug: "derenne-plaza", name: "Derenne Plaza", zip: "31405" },
  { slug: "downtown", name: "Downtown", zip: "31401" },
  { slug: "east-savannah", name: "East Savannah", zip: "31404" },
  { slug: "fairmont", name: "Fairmont", zip: "31406" },
  { slug: "forest-park", name: "Forest Park", zip: "31406" },
  { slug: "georgetown", name: "Georgetown", zip: "31419" },
  { slug: "gordonston", name: "Gordonston", zip: "31404" },
  { slug: "grove-park", name: "Grove Park", zip: "31405" },
  { slug: "highland-park", name: "Highland Park", zip: "31405" },
  { slug: "isle-of-hope", name: "Isle of Hope", zip: "31406" },
  { slug: "kensington-park", name: "Kensington Park", zip: "31404" },
  { slug: "lake-mayer", name: "Lake Mayer", zip: "31406" },
  { slug: "largo-woods", name: "Largo Woods", zip: "31406" },
  { slug: "live-oak", name: "Live Oak", zip: "31401" },
  { slug: "magnolia-park", name: "Magnolia Park", zip: "31405" },
  { slug: "midtown", name: "Midtown", zip: "31405" },
  { slug: "moon-river", name: "Moon River", zip: "31406" },
  { slug: "oakdale", name: "Oakdale", zip: "31405" },
  { slug: "oakhurst", name: "Oakhurst", zip: "31404" },
  { slug: "parkside", name: "Parkside", zip: "31404" },
  { slug: "pine-gardens", name: "Pine Gardens", zip: "31405" },
  { slug: "pinecrest", name: "Pinecrest", zip: "31406" },
  { slug: "savannah-gardens", name: "Savannah Gardens", zip: "31404" },
  { slug: "skyland-terrace", name: "Skyland Terrace", zip: "31404" },
  { slug: "southbridge", name: "Southbridge", zip: "31405" },
  { slug: "springhill", name: "Springhill", zip: "31405" },
  { slug: "tatemville", name: "Tatemville", zip: "31405" },
  { slug: "the-landings", name: "The Landings", zip: "31411" },
  { slug: "twickenham", name: "Twickenham", zip: "31406" },
  { slug: "vernonburg", name: "Vernonburg", zip: "31406" },
  { slug: "victory-heights", name: "Victory Heights", zip: "31404" },
  { slug: "victorian-district", name: "Victorian District", zip: "31401" },
  { slug: "windsor-forest", name: "Windsor Forest", zip: "31406" },
  { slug: "woodville", name: "Woodville", zip: "31415" },
]
